<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <PackageVersion>1.4.0</PackageVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.8"/>
    <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.8"/>
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.8"/>
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.8">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
    <PackageReference Include="LibVLCSharp.Avalonia" Version="3.9.3" />
    <PackageReference Include="Material.Avalonia" Version="3.11.0" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReactiveUI" Version="20.2.45" />
    <PackageReference Include="semi.avalonia" Version="11.2.1.7" />
    <PackageReference Include="System.Text.Json" Version="9.0.5" />
    <PackageReference Include="TinyMapper" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\FavoriteListView.axaml.cs">
      <DependentUpon>FavoriteView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\MineView.axaml.cs">
      <DependentUpon>MineView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\WorkListView.axaml.cs">
      <DependentUpon>PoetriesView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\WorkView.axaml.cs">
      <DependentUpon>WorkView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MobileNavigation.axaml.cs">
      <DependentUpon>MobileNavigation.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\InteractiveContainer.axaml.cs">
      <DependentUpon>InteractiveContainer.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\HorizontalSeparator.axaml.cs">
      <DependentUpon>HorizontalSeparator.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\SliverPage.axaml.cs">
      <DependentUpon>SliverPage.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\GroupBox.axaml.cs">
      <DependentUpon>GroupBox.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFields\FormFieldAction.axaml.cs">
      <DependentUpon>FormFieldAction.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFields\FormFieldNumberPicker.axaml.cs">
      <DependentUpon>FormFieldNumberPicker.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFields\FormFieldPicker.axaml.cs">
      <DependentUpon>FormFieldPicker.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFields\FormFieldSwitch.axaml.cs">
      <DependentUpon>FormFieldSwitch.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MobilePicker\MobilePicker.axaml.cs">
      <DependentUpon>MobilePicker.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MobilePicker\MobilePickerPopUp.axaml.cs">
      <DependentUpon>MobilePickerPopUp.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MobilePicker.axaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MobilePickerPopUp.axaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFieldAction.axaml.cs">
      <DependentUpon>FormFieldAction.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFieldNumberPicker.axaml.cs">
      <DependentUpon>FormFieldNumberPicker.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFieldPicker.axaml.cs">
      <DependentUpon>FormFieldPicker.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\FormFieldSwitch.axaml.cs">
      <DependentUpon>FormFieldSwitch.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MobileNumberPicker.axaml.cs">
      <DependentUpon>MobileNumberPicker.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\MobileNumberPickerPopup.axaml.cs">
      <DependentUpon>MobileNumberPickerPopup.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\CollectionListView.axaml.cs">
      <DependentUpon>CollectionListView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\CollectionListItemView.axaml.cs">
      <DependentUpon>CollectionListItemView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\CollectionView.axaml.cs">
      <DependentUpon>CollectionView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\FavoriteListItemView.axaml.cs">
      <DependentUpon>FavoriteListItemView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\LogItemView.axaml.cs">
      <DependentUpon>LogItemView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoetryPlanet.Core\PoetryPlanet.Core.csproj" />
    <ProjectReference Include="..\PoetryPlanet.Data\PoetryPlanet.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="PoetryPlanet.csproj.DotSettings" />
  </ItemGroup>

</Project>
