<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <PackageVersion>1.4.0</PackageVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.8"/>
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.8"/>
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.8"/>
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.8">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Material.Avalonia" Version="3.11.0" />
    <PackageReference Include="Material.Icons.Avalonia" Version="2.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="ReactiveUI" Version="20.2.45" />
    <PackageReference Include="semi.avalonia" Version="11.2.1.7" />
    <PackageReference Include="System.Text.Json" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CherylUI">
      <HintPath>..\..\..\CherylUI\CherylUI\bin\Debug\netstandard2.0\CherylUI.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\FavoriteWorksView.axaml.cs">
      <DependentUpon>FavoriteView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\MineView.axaml.cs">
      <DependentUpon>MineView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\NavigationView.axaml.cs">
      <DependentUpon>NavigationView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\WorkListView.axaml.cs">
      <DependentUpon>PoetriesView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\WorkView.axaml.cs">
      <DependentUpon>WorkView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\FavoriteWorkView.axaml.cs">
      <DependentUpon>FavoriteWorkView.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PoetryPlanet.Core\PoetryPlanet.Core.csproj" />
  </ItemGroup>
</Project>
