kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
  namespace: poetry-planet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
